inherit_from: ".rubocop.yml"

plugins:
  - rubocop-md

AllCops:
  Include:
    - '**/*.md'

Naming/FileName:
  Exclude:
   - '**/*.md'

Layout/InitialIndentation:
  Exclude:
    - 'CHANGELOG.md'

Layout/IndentationConsistency:
  Enabled: false
