name: Lint Docs

on:
  push:
    branches:
      - main
    paths:
      - "**/*.md"
      - ".github/workflows/docs-lint.yml"
  pull_request:
    paths:
      - "**/*.md"
      - ".github/workflows/docs-lint.yml"

jobs:
  docs-lint:
    uses: anycable/github-actions/.github/workflows/docs-lint.yml@master
    with:
      forspell-args: "**/*.md *.md -e BACKERS.md"
      lychee-args: docs/* --exclude "(rails/|anycable-go/|deployment/|architecture.md)" -v README.md CHANGELOG.md
